# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## Base settings ##
url: "https://yearningz.github.io" #The site's Protocol and Hostname e.g. https://blog.someone.com (!!required!!)
title: yearning_z
description: > #this means to ignore newlines until "base_path:"
    jie

##* Home base settings ##
baseurl: "/"
avata_url: https://wx1.sinaimg.cn/mw690/77025ef7ly8fl3kqeo8n6j20ku0ku74k.jpg

##* Blog base settings ##
blog:
  baseurl: "/blog"
  title: Jie's blog
  description: Jie's Blog | yearning_z的博客
  nav_lists:
    - title: About
      url: /blog/about.html
##* Artsworks base settings ##
artworks:
  baseurl: ""

## GitHub repository (if the site is hosted by GitHub) ##
repository: yearningz/yearningz.github.io
repository_tree: master

## Language & timezone ##
lang: zh # the language of your site
timezone: Asia/Shanghai

## Author & social ##
author:
  name: "jie"
  email: 121110901@qq.com
  github:  yearningz
  weibo: yearning_z
  douban: yearning_z

## Comment system (Disqus) ##
disqus:
  shortname: yearningz-github-io

## Google Analytics ##
ga_tracking_id:

## Reading quantity (LeanCloud) ##
leancloud:
  app_id:
  app_key:
  app_class:

## Paginate ##
paginate: 7
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

## Plugins ##
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false
